version: '3.1'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_DIR}/website:/usr/share/nginx/html
      - ${NGINX_DIR}/conf.d:/etc/nginx/conf.d
