version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DIR}/conf.d:/etc/mysql/conf.d
      - ${MYSQL_DIR}/data:/var/lib/mysql
