services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "${MINIO_API_PORT}:9000" # API端口
      - "${MINIO_CONSOLE_PORT}:9001" # 控制台端口
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # 设置管理员用户名
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # 设置管理员密码
    volumes:
      - ${MINIO_DIR}:/data # 数据持久化
    command: server --console-address ":9001" /data # 启动服务器并指定控制台端口
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
