version: '3.1'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --include /usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DIR}/data:/data
      - ${REDIS_DIR}/redis.conf:/usr/local/etc/redis/redis.conf
